conda-forge/setuptools-feedstock

- recipe/meta.yaml
This adds `certifi` and `wincertstore` as dependencies as `setuptools` intends. While we have to stop `setuptools` from downloading these via [`extras_require`]( https://github.com/conda-forge/setuptools-feedstock/blob/00e1314b0a34895fe4b050f6d049edc811e6f567/recipe/setup.patch ), we should still be able to provide them. Especially as we do have them. This PR does that.
We may want to soften the `setuptools` requirement in `certifi` via PR ( https://github.com/conda-forge/certifi-feedstock/pull/7 ) before we go ahead with this. Hence I have marked this as WIP. `wincertstore` already has a soft dependency on `setuptools` and is installed via `distutils` ATM.
> Add dependencies `certifi` and `wincertstore`

- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
This bumps the version to 25.2.0 and includes the new license file. In order to do the latter, we switched to GitHub for the source.
**Changelog:**
```
v25.2.0
-------
* #612 via #730: Add a LICENSE file which needs to be provided by the terms of
the MIT license.
```
> Bump to 25.2.0 and include new license file

- recipe/meta.yaml
Changes:
```
v25.3.0
-------
* #739 Fix unquoted libpaths by fixing compatibility between `numpy.distutils` and `distutils._msvccompiler` for numpy < 1.11.2 (Fix issue #728, error also fixed in Numpy).
* #731: Bump certifi.
* Style updates. See #740, #741, #743, #744, #742, #747.
* #735: include license file.
```
> Bump to 25.3.0

- recipe/meta.yaml
Changes:
```
v25.4.0
-------
* Add Extension(py_limited_api=True). When set to a truthy value,
that extension gets a filename apropriate for code using Py_LIMITED_API.
When used correctly this allows a single compiled extension to work on
all future versions of CPython 3.
The py_limited_api argument only controls the filename. To be
compatible with multiple versions of Python 3, the C extension
will also need to set -DPy_LIMITED_API=... and be modified to use
only the functions in the limited API.
```
> Bump to 25.4.0

- recipe/meta.yaml
Changes:
```
v26.0.0
-------
* #748: By default, sdists are now produced in gzipped tarfile
format by default on all platforms, adding forward compatibility
for the same behavior in Python 3.6 (See Python #27819).
* #459 via #736: On Windows with script launchers,
sys.argv[0] now reflects
the name of the entry point, consistent with the behavior in
distlib and pip wrappers.
* #752 via #753: When indicating ``py_limited_api`` to Extension,
it must be passed as a keyword argument.
```
> Bump to 26.0.0

- recipe/meta.yaml
Changes:
```
v26.1.0
-------
* #763: ``pkg_resources.get_default_cache`` now defers to the
`appdirs project <https://pypi.org/project/appdirs>`_ to
resolve the cache directory. Adds a vendored dependency on
appdirs to pkg_resources.
```
> Bump to 26.1.0

- .travis.yml
- README.md
- recipe/meta.yaml
Also updated `home` as that changed was changed some time ago (March 2016) in PR ( https://github.com/pypa/setuptools/pull/560 ).
Changes:
```
v26.1.1
* Re-release of 26.1.0 with pytest pinned to allow for automated deployement and thus proper packaging environment variables, fixing issues with missing executable launchers.
```
> Bump to 26.1.1

- recipe/meta.yaml
``` rst
v27.0.0
-------
* Now use Warehouse by default for
``upload``, patching ``distutils.config.PyPIRCCommand`` to
affect default behavior.
Any config in .pypirc should be updated to replace
https://pypi.python.org/pypi/
with
https://upload.pypi.org/legacy/
Similarly, any passwords stored in the keyring should be
updated to use this new value for "system".
The ``upload_docs`` command will continue to use the python.org
site, but the command is now deprecated. Users are urged to use
Read The Docs instead.
* #776: Use EXT_SUFFIX for py_limited_api renaming.
* #774 and #775: Use LegacyVersion from packaging when
detecting numpy versions.
```
> Release 27.0.0

- recipe/meta.yaml
Replaces https://github.com/conda-forge/setuptools-feedstock/pull/23 ( `27.1.1` )
```rst
v27.1.2
-------
* #779 via #781: Fix circular import.
v27.1.1
-------
* #778: Fix MSVC monkeypatching.
```
> Release 27.1.2

- recipe/meta.yaml
```rst
v27.2.0
-------
* #520 and #513: Suppress ValueErrors in fixup_namespace_packages
when lookup fails.
* Nicer, more consistent interfaces for msvc monkeypatching.
```
> Release 27.2.0

- recipe/meta.yaml
```rst
v27.3.0
-------
* #794: In test command, add installed eggs to PYTHONPATH
when invoking tests so that subprocesses will also have the
dependencies available. Fixes `tox 330
<https://github.com/tox-dev/tox/issues/330>`_.
* #795: Update vendored pyparsing 2.1.9.
```
> Release 27.3.0

- recipe/meta.yaml
```rst
v27.3.1
-------
* #790: In MSVC monkeypatching, explicitly patch each
function by name in the target module instead of inferring
the module from the function's ``__module__``. Improves
compatibility with other packages that might have previously
patched distutils functions (i.e. NumPy).
```
> Release 27.3.1

- recipe/meta.yaml
```rst
v28.0.0
-------
* #733: Do not search excluded directories for packages.
This introduced a backwards incompatible change in ``find_packages()``
so that ``find_packages(exclude=['foo']) == []``, excluding subpackages of ``foo``.
Previously, ``find_packages(exclude=['foo']) == ['foo.bar']``,
even though the parent ``foo`` package was excluded.
* #795: Bump certifi.
* #719: Suppress decoding errors and instead log a warning
when metadata cannot be decoded.
```
> Release 28.0.0

- recipe/meta.yaml
```rst
v28.3.0
-------
* #809: In ``find_packages()``, restore support for excluding
a parent package without excluding a child package.
* #805: Disable ``-nspkg.pth`` behavior on Python 3.3+ where
PEP-420 functionality is adequate. Fixes pip #1924.
```
---
**Note:** 28.2.0 and 28.3.0 are identical. So we skipped the former. Plus
there is no changelog entry for the former so we used the latter. There
may have been issues uploading to PyPI or similar.
**Additional note:** 28.1.0 amounted to an adjustment of the certifi link.
As such, it seems totally unnecessary to build a conda package for it as
one could use 28.0.0 just the same.
> Release 28.3.0

- recipe/meta.yaml
```rsr
v28.4.0
-------
* #732: Now extras with a hyphen are honored per PEP 426.
* #811: Update to pyparsing 2.1.10.
* Updated ``setuptools.command.sdist`` to re-use most of
the functionality directly from ``distutils.command.sdist``
for the ``add_defaults`` method with strategic overrides.
See #750 for rationale.
* #760 via #762: Look for certificate bundle where SUSE
Linux typically presents it. Use ``certifi.where()`` to locate
the bundle.
```
> Release 28.4.0

- recipe/meta.yaml
```rst
v28.5.0
-------
* #810: Tests are now invoked with tox and not setup.py test.
* #249 and #450 via #764: Avoid scanning the whole tree
when building the manifest.
```
> Release 28.5.0

- recipe/meta.yaml
```rst
v28.6.0
-------
* #629: When scanning for packages, ``pkg_resources`` now
ignores empty egg-info directories and gives precedence to
packages whose versions are lexicographically greatest,
a rough approximation for preferring the latest available
version.
```
> Release 28.6.0

- recipe/meta.yaml
```rst
v28.7.0
-------
* #832: Moved much of the namespace package handling
functionality into a separate module for re-use in something
like #789.
* #830: ``sdist`` command no longer suppresses the inclusion
of data files, re-aligning with the expectation of distutils
and addressing #274 and #521.
```
> Release 28.7.0

- recipe/meta.yaml
```rst
v28.7.1
-------
* #827: Update PyPI root for dependency links.
* #833: Backed out changes from #830 as the implementation
seems to have problems in some cases.
```
> Release 28.7.1

- recipe/meta.yaml
```rst
v28.8.0
-------
* #629: Per the discussion, refine the sorting to use version
value order for more accurate detection of the latest
available version when scanning for packages. See also
#829.
* #837: Rely on the config var "SO" for Python 3.3.0 only
when determining the ext filename.
```
> Release 28.8.0

- recipe/meta.yaml
v29.0.0
-------
* #841: Drop special exception for packages invoking
win32com during the build/install process. See
Distribute #118 for history.
> Release 29.0.0

- recipe/meta.yaml
v29.0.1
-------
* #861: Re-release of v29.0.1 with the executable script
launchers bundled. Now, launchers are included by default
and users that want to disable this behavior must set the
environment variable
'SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES' to
a false value like "false" or "0".
> Release 29.0.1

- recipe/meta.yaml
```
v31.0.0
-------
* #250: Install '-nspkg.pth' files for packages installed
with 'setup.py develop'. These .pth files allow
namespace packages installed by pip or develop to
co-mingle. This change required the removal of the
change for #805 and pip #1924, introduced in 28.3.0 and implicated
in #870, but means that namespace packages not in a
site packages directory will no longer work on Python
earlier than 3.5, whereas before they would work on
Python not earlier than 3.3.
```
> Update to 31.0.0

- recipe/meta.yaml
ppc64le builds were marked broken
> bump build number due to travis

- .github/CODEOWNERS
- conda-forge.yml
- recipe/meta.yaml
Hi! This is the friendly automated conda-forge-webservice.
I've added user @rgommers as instructed in #231.
Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.
Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.
Fixes #231
> [ci skip] adding user @rgommers

- .github/CODEOWNERS
- README.md
- conda-forge.yml
- recipe/meta.yaml
This is needed because multiple projects need to pin to `setuptools < 60.0`, which was the release that enabled the
vendored copy of `distutils` inside `setuptools`. That `distutils` copy contains backwards incompatible changes which
NumPy and SciPy don't support; other projects like Pandas and Dask use that pin too because of the `LooseVersion` deprecation in 60.0
See https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/204 for more details.
`[ci skip]`
Also add myself as recipe maintainer.
**Note:** @beckermr suggested a procedure at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/204#issuecomment-1013718192 that involves adding a branch to this repo (it should be named `59_x` like in this PR). I don't have permissions to push that …
> Add a 59.x LTS branch

- recipe/meta.yaml
Some `ppc64le` builds hadn't made it up when PR ( https://github.com/conda-forge/setuptools-feedstock/pull/254 ) was merged. So this bumps the build number again to fix those.
cc @isuruf (for awareness)
Checklist
> Rebuild for PyPy 3.8 & 3.9 migration (again)

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Unpin Python in tests
